[package]
name = "elden_mod_loader_gui"
version = "0.1.0"
authors = ["cal_b"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.3"
native-dialog = "0.7.0"
log = "0.4.20"
env_logger = "0.11.0"
rust-ini = "0.20.0"

[build-dependencies]
slint-build = "1.3"
