[package]
name = "elden_mod_loader_gui"
version = "0.9.18"
authors = ["WardLordRuby"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.winresource]
ProductName = "Elden Mod Loader GUI"
FileDescription = "A UI tool made by: WardLordRuby"
ProductVersion = "0.9.18-beta"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true

[dependencies]
slint = "1.5.1"
i-slint-backend-winit = "1.5.1"
winit = "0.29.15"
native-dialog = "0.7.0"
log = "0.4.21"
env_logger = "0.11.3"
rust-ini = "0.21.0"
lazy_static = "1.4.0"

[build-dependencies]
slint-build = "1.5.1"
winresource = "0.1.17"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "data_collection_benchmark"
harness = false
