import { Button, StandardButton } from "std-widgets.slint";
import { MainPage, MainLogic, DisplayMod } from "main.slint";
import { SettingsLogic } from "settings.slint";

export { MainLogic, SettingsLogic, DisplayMod }

export component App inherits Window {
    in-out property <int> focus_page;
    in property <string> err-message;
    preferred-height: 370px;
    min-height: 270px;
    width: 315px;
    
    MainPage {}

    callback show_error_popup;
    show_error_popup => { err-popup.show(); }

    // Make popupWindow look nice 
    err_popup := PopupWindow {
        x: root.width / 2.7;
        y: root.height / 2.7;
        width: min(err_popup_layout.preferred-width, root.width - 80px);
        close-on-click: false;

        Rectangle {
            background: root.background;
            border-color: err_popup_text.color;
            border-width: 1px;
        }

        err_popup_layout := Dialog {
            height:100%; width: 100%;

            err_popup_text := Text {
                text: root.err-message;
                wrap: word-wrap;
            }

            StandardButton { kind: ok; clicked => { err-popup.close(); } }
        }
    }
}