export struct DisplayMod  {
    displayname: string,
    name: string,
    enabled: bool,
    files: string,
    has-config: bool,
    config-files: [string],
}

export enum Message { confirm, deny, esc }

export global MainLogic {
    callback toggleMod(string, bool);
    callback select_mod_files(string);
    callback add_to_mod(string);
    callback remove_mod(string);
    callback edit_config([string]);
    callback force_app_focus();
    callback send_message(Message);
    in property <string> line_edit_text;
    in-out property <bool> if-err-bool;
    in-out property <bool> game_path_valid;
    in-out property <int> current_subpage: 0;
    in-out property <[DisplayMod]> current_mods: [
        {displayname: "Placeholder Name", name: "Placeholder Name", enabled: true, files: "\\placeholder\\path\\data"},
        {displayname: "Placeholder Name", name: "Placeholder Name Two", enabled: false, files: "\\placeholder\\path\\data"},
        {displayname: "Placeholder Name", name: "Placeholder Name Three", enabled: true, files: "\\placeholder\\path\\data"},
    ];
}

export global SettingsLogic  {
    callback select_game_dir();
    callback open_game_dir();
    callback toggle_theme(bool);
    callback toggle_terminal(bool);
    callback set_load_delay(string);
    callback toggle_all(bool);
    in property <string> game_path: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ELDEN RING\\Game";
    in property <bool> loader_installed;
    in-out property <bool> dark_mode: true;
    in-out property <bool> loader_disabled;
    in-out property <bool> show_terminal;
    in-out property <string> load_delay: "5000ms";
    in property <string> delay_input;
}

struct ButtonColors  {
    pressed: color,
    hovered: color,
}

export global ColorPalette  {
    out property <color> page-background-color: SettingsLogic.dark_mode ? #1b1b1b : #60a0a4;
    out property <color> popup-background-color: SettingsLogic.dark_mode ? #00393d : #1b1b1b;
    out property <color> popup-border-color: SettingsLogic.dark_mode ? #17575c : #1b1b1b;

    out property <color> text-foreground-color: #ffffff;
    out property <color> text-base: #aeaeae;
    out property <ButtonColors> text-shade-colors: {
        pressed: SettingsLogic.dark_mode ? root.text-base.darker(30%) : root.text-base.darker(10%),
        hovered: root.text-base.brighter(20%),
    };

    out property <color> button-image-base: SettingsLogic.dark_mode ? #505150 : #aeaeae;
    out property <ButtonColors> button-image-colors: {
        pressed: root.button-image-base.darker(40%),
        hovered: root.button-image-base.brighter(20%),
    };
    out property <color> button-background-base: SettingsLogic.dark_mode ? #4b4b4b83 : #6fc5ffaf;
    out property <ButtonColors> button-background-colors: {
        pressed: root.button-background-base.darker(40%),
        hovered: root.button-background-base.darker(20%),
    };
}

export component Page inherits Rectangle {
    in property<string> title: "title";
    in property<string> description: "description";
    in property <bool> has-back-button;
    width: 310px;
    background: ColorPalette.page-background-color;

    callback back;
    callback settings;
    back => { MainLogic.current-subpage = 0 }
    settings => { MainLogic.current-subpage = 1 }

    TouchArea {} // Protect underneath controls

    HorizontalLayout {
        x: 0;
        y: 0;
        height: 48px;
        padding-left: 5px;
        padding-right: 8px;
        padding-top: 8px;

        if (root.has-back-button) : HorizontalLayout {
            im1 := Image {
                source: @image-url("assets/back-arrow.png");
                image-fit: contain;
                colorize: ColorPalette.text-foreground-color;
                source-clip-y: -50;
                width: 30px;
                height: 24px;
                
                ta1 := TouchArea {
                    x:0;
                    height: 37px;
                    width: title.width + im1.width;
                    clicked => { root.back() }
                }
            }
            title := Text {
                font-size: 24px;
                max-width: root.width - 10px;
                text: root.title;
                color: ColorPalette.text-foreground-color;
                overflow: elide;
            }

            Rectangle {} // Spacer

            states [
                hover when ta1.has-hover && !ta1.pressed: {
                    title.color: ColorPalette.text-shade-colors.hovered;
                    im1.colorize: ColorPalette.text-shade-colors.hovered;
                }
                pressed when ta1.pressed : {
                    title.color: ColorPalette.text-shade-colors.pressed;
                    im1.colorize: ColorPalette.text-shade-colors.pressed;
                }
            ]
        }
        
        if (!root.has-back-button) : HorizontalLayout {
            Text {
                font-size: 24px;
                max-width: root.width * 0.8;
                text: root.title;
                color: ColorPalette.text-foreground-color;
                overflow: elide;
            }

            Rectangle {} // Spacer

            re := Rectangle {
                width: 33px;
                height: 33px;
                border-radius: 4px;
                im2 := Image {
                    source: @image-url("assets/settings.png");
                    colorize: ColorPalette.button-image-base;
                    width: 28px;
                    image-fit: contain;
                    ta2 := TouchArea {
                        width: 45px;
                        height: 40px;
                        clicked => { root.settings() }
                    }
                }
                states [
                    hover when ta2.has-hover && !ta2.pressed: {
                        re.background: ColorPalette.button-background-colors.hovered;
                        im2.colorize: ColorPalette.button-image-colors.hovered;
                    }
                    pressed when ta2.pressed : {
                        re.background: ColorPalette.button-background-colors.pressed;
                        im2.colorize: ColorPalette.button-image-colors.pressed;
                    }
                ]
            }
        }
    }
    @children
}