import { GroupBox, Button, HorizontalBox, Switch } from "std-widgets.slint";
import { MainLogic, Page } from "common.slint";

export component ModDetailsPage inherits Page {
    has-back-button: true;
    property <length> box-width: game-path-box.width - 10px;
    in property <int> mod-index;
    title: MainLogic.current_mods[mod-index].name;
    description: @tr("Edit registered mods here");


    VerticalLayout {
        y: 38px;
        height: parent.height - self.y;
        padding-left: 8px;
        padding-right: 0px;
        spacing: 0px;
        preferred-width: 460px;
        alignment: start;
        
        game-path-box := GroupBox {
            title: @tr("Details");
            padding: 0px;
            Text {
                font-size: 8pt;
                text: @tr("Name:");
            }
            HorizontalBox {
                row: 1;
                width: box-width;

                Text {
                    font-size: 12pt;
                    wrap: word-wrap;
                    text: MainLogic.current_mods[mod-index].name;
                }
            }
            Text {
                row: 2;
                font-size: 8pt;
                text: @tr("Files:");
            }
            HorizontalBox {
                row: 2;
                width: box-width;
                padding-top: 16px;

                Text {
                    font-size: 12pt;
                    wrap: word-wrap;
                    text: MainLogic.current_mods[mod-index].files;
                }
            }
        }
        GroupBox {
            title: @tr("Edit Mod");
            HorizontalBox {
                width: box-width;
                padding-top: 7px;
                alignment: end;
                Button {
                    width: 105px;
                    height: 35px;
                    text: @tr("Add Files");
                    clicked => {}
                }
                Button { 
                    width: 105px;
                    height: 35px;
                    text: @tr("De-register");
                    clicked => {}
                }
            }
        }
    }
}