import { GroupBox, Button, ScrollView } from "std-widgets.slint";
import { MainLogic, Page } from "common.slint";

export component ModDetailsPage inherits Page {
    has-back-button: true;
    title: MainLogic.current_mods[mod-index].name;
    description: @tr("Edit registered mods here");
    property <length> box-width: details.width - 10px;
    in property <int> mod-index;
    in property <color> state-color;
    in property <string> state;

    VerticalLayout {
        y: 38px;
        height: root.height - edit-mod-box.height - 27px;
        padding-left: 8px;
        padding-right: 0px;
        spacing: 0px;
        preferred-width: 460px;
        alignment: start;
        
        details := GroupBox {
            title: @tr("Details");
            height: parent.height;
            GridLayout {
                height: 25px;
                Text {
                    width: root.width * 0.56;
                    vertical-alignment: bottom;
                    col: 0;
                    font-size: 8pt;
                    text: @tr("Name:");
                }
                Text {
                    horizontal-alignment: right;
                    vertical-alignment: center;
                    col: 1;
                    font-size: 8pt;
                    text: @tr("Enabled:  ");
                }
                Text {
                    horizontal-alignment: left;
                    col: 2;
                    font-size: 16pt;
                    color: state-color;
                    text: state;
                }
            }
            VerticalLayout {
                spacing: 2px;
                row: 1;
                width: box-width;
                mod-name-txt := Text {
                    vertical-alignment: center;
                    min-height: 24px;
                    font-size: 12pt;
                    wrap: word-wrap;
                    text: MainLogic.current_mods[mod-index].name;
                }
                Text {
                    font-size: 8pt;
                    text: @tr("Files:");
                }
                ScrollView {
                    viewport-height: files-txt.height;
                    files-txt := Text {
                        x: 5px;
                        y: 4px;
                        font-size: 12pt;
                        wrap: word-wrap;
                        text: MainLogic.current_mods[mod-index].files;
                    }
                }
            }
        }
    }
    HorizontalLayout {
        y: root.height - edit-mod-box.height;
        height: root.height - self.y;
        padding-left: 8px;
        spacing: 0px;
        preferred-width: 460px;
        edit-mod-box := GroupBox {
            title: @tr("Edit Mod");
            width: parent.width - parent.padding-left;
            height: 95px;
            HorizontalLayout {
                width: box-width;
                spacing: 7px;
                alignment: end;
                Button {
                    width: 105px;
                    height: 35px;
                    text: @tr("Add Files");
                    clicked => { MainLogic.add_to_mod(MainLogic.current_mods[mod-index].name) }
                }
                Button { 
                    width: 105px;
                    height: 35px;
                    text: @tr("De-register");
                    clicked => { MainLogic.remove_mod(MainLogic.current_mods[mod-index].name) }
                }
            }
        }
    }
}