import { HorizontalBox } from "std-widgets.slint";

export component Page inherits Rectangle {
    in property<string> title: "title";
    in property<string> description: "description";
    in property <bool> has-back-button;
    width: 310px;
    background: #1b1b1b;

    callback back;
    callback settings;

    TouchArea {} // Protect underneath controls

    HorizontalBox {
        x: 0;
        y: 0;
        height: 48px;
        padding-left: 5px;
        padding-right: 5px;


        if (root.has-back-button) : Image {
            source: @image-url("assets/back-arrow.png");
            image-fit: contain;
            colorize: #ffffff;
            y: 2px;
            width: 30px;
            height: 24px;
    
            TouchArea {
                clicked => { root.back() }
                x:0;
                height: 37px;
                width: 400%;
            }
        }

        if (root.has-back-button) : Rectangle {
            height: 28px;
            width: 5px;
        }

        Text {
            font-size: 24px;
            vertical-alignment: center;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}

        if (!root.has-back-button) : re := Rectangle {
            width: 33px;
            height: 33px;
            border-radius: 4px;
            y: -3px;
            im := Image {
                source: @image-url("assets/settings.png");
                colorize: #505150;
                width: 28px;
                image-fit: contain;
                ta := TouchArea {
                    clicked => { root.settings() }
                    width: 45px;
                    height: 40px;
                    
                }
            }
            states [
                hover when ta.has-hover && !ta.pressed: {
                    re.background: #4b4b4b;
                    im.colorize: #1f1f1f;
                }
                pressed when ta.pressed : {
                    re.background: #3b3b3b;
                    im.colorize: #292828;
                }
            ]
        }
    }
    @children
}