import { GroupBox, Button, HorizontalBox, LineEdit, Switch } from "std-widgets.slint";

import { Page } from "page.slint";

export global SettingsLogic  {
    callback select_game_dir();
    in property <string> game_path: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ELDEN RING\\Game";
}

export component SettingsPage inherits Page {
    has-back-button: true;
    title: @tr("Settings");
    description: @tr("Set path to eldenring.exe and register mods here");


    VerticalLayout {
        y: 38px;
        height: parent.height - self.y;
        padding-left: 8px;
        spacing: 0px;
        preferred-width: 460px;
        alignment: start;
        
        game-path-box := GroupBox {
            title: @tr("Game Path");
            padding: 0px;

            HorizontalBox {
                row: 1;
                width: game-path-box.width - 10px;

                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                    text: SettingsLogic.game_path;
                }
            }
            HorizontalBox {
                row: 2;
                alignment: end;
                select-game := Button { 
                    width: 105px;
                    height: 35px;
                    text: @tr("Set Path");
                    clicked => {
                        SettingsLogic.select_game_dir();
                    }
                }
            }
        }
        GroupBox {
            title: @tr("Theme");
            HorizontalBox {
                padding-top: 7px;
                Switch {
                    text: @tr("DarkMode");
                }
            }
        }
    }
}